# Generated by Django 3.1.2 on 2020-10-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number_ofplayers',
            new_name='number_of_players',
        ),
    ]
