# Generated by Django 3.1.2 on 2020-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20201103_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
