# Generated by Django 3.1.2 on 2020-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20201103_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='maker', max_length=75),
        ),
    ]
