# Generated by Django 3.1.2 on 2020-11-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_game_maker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGamer',
            new_name='EventGamers',
        ),
    ]
